services:
    auth-database:
        build: ./auth-database
        restart:  on-failure
        ports:
            - "3306:3306"
        env_file: 
            - ./auth-database/auth.env
        networks:
            bearchat:
                ipv4_address:
                    172.28.1.2
        expose: 
            - '3306'
    
    posts-database:
        build: ./posts-db
        restart:  on-failure
        ports:
            - "3307:3306"
        env_file: 
            - ./posts-db/posts.env
        networks:
            bearchat:
                ipv4_address:
                    172.28.1.3
        expose: 
            - '3307'
    
    auth-service:
        build: ./auth-service
        restart:  on-failure
        ports:
            - "80:80"
        networks:
            bearchat:
                ipv4_address:
                    172.28.1.1
        depends_on:
          - auth-database

        expose: 
            - '80'

networks:
    bearchat:
        ipam:
            config:
                - subnet: 172.28.0.0/16